### ISSUE TITLE
Could I trouble you to release a new version with the last fix?

### ISSUE THREAD

**Issue by demus-nine** [virtualdogbert/enterprise-groovy-plugin#13]
I'm upgrading af bunch of projects and adding the plugin, but i have to copy the templates around manually.

**Comment by virtualdogbert** [comment]
I'll see if I can get to it soon, maybe tonight, but by the weekend at the latest.

**Comment by demus-nine** [comment]
Great, thanks. I hope it'll also be a boon to others.

**Comment by virtualdogbert** [comment]
I'm sure it couldn't hurt, although I've been surprised in the surge of downloads starting this year:
https://bintray.com/virtualdogbert/maven/enterprise-groovy#statistics

**Comment by virtualdogbert** [comment]
Ok just release 1.0.5, funny someone was asking about having static compilation by default for Grails, and this fixes a problem they would have run into if they used my plugin. Thanks.
