### ISSUE TITLE
getConfigFile() fails with NullPointerException for templates

### ISSUE THREAD

**Issue by apryamostanov** [virtualdogbert/enterprise-groovy-plugin#7]
Hi @virtualdogbert ,

`getConfigFile` fails with NullPointerException in [virtualdogbert/enterprise-groovy#1](https://github.com/virtualdogbert/enterprise-groovy/pull/1) because `sourceUnit.getConfiguration().getTargetDirectory()` is `null` for templates (and I assume possible in other scenarios as well, when there is non-file based compilation.

**Comment by apryamostanov** [comment]
Please see stack trace in #6

**Comment by virtualdogbert** [comment]
sourceUnit.getConfiguration().getTargetDirectory() was one of the only reliable ways I could get at the source directory, For this I'm thinking that If I can't get the targetDirectory, i.e. a script being run, maybe I just bail out of the AST...

**Comment by apryamostanov** [comment]
Seems as a feasible option, to terminate at a point where non-file based source unit is transformed.

**Comment by virtualdogbert** [comment]
Made scripts which can't get the target directory skip the AST transform by default.
