### ISSUE TITLE
Enterprise plugin affecting other builds

### ISSUE THREAD

**Issue by apryamostanov** [virtualdogbert/enterprise-groovy-plugin#8]
Hi @virtualdogbert ,

I noticed that with several Idea (Gradle) projects - if I build a project with Groovy Enterprise Plugin, it sometimes stays in the Gradle process in RAM and is affecting other builds, even where it is not applied.

This is probably a general issue for Global AST transformations.

**Comment by apryamostanov** [comment]
Or it can be related to some caches in ./gradle

**Comment by apryamostanov** [comment]
In fact I can see that somehow the plugin dependency is exported in POM:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.infinite</groupId>
  <artifactId>supplies</artifactId>
  <version>1.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.virtualdogbert</groupId>
      <artifactId>enterprise-groovy</artifactId>
      <version>1.0.RC2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.5.4</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by apryamostanov** [comment]
This happens with Artifactory publish Gradle plugin with same "Supplies" project.

**Comment by apryamostanov** [comment]
Check problematic POM view: 
https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/PomView/oss-snapshot-local/io/infinite/supplies/1.0.1-SNAPSHOT/supplies-1.0.1-20190212.103344-30.pom

**Comment by apryamostanov** [comment]
So actual question: how to exclude this dependency from POM?

**Comment by virtualdogbert** [comment]
Hmm, well the gradle plugin adds the library as a compile dependency to the project you apply it to. So if you are applying it to a library, then you would get it as a transitive dependency. So maybe what I should do is make it configurable, so that you can decide, how it is applied to your project, compile, implementation, etc.  However in one of the other open tickets, If I'm not using the apply syntax, adding the dependency doesn't work, so I have to figure out another way to do that for gradle 5, with the plugin dsl.

**Comment by apryamostanov** [comment]
hi @virtualdogbert , it seems that bare presence of Global transformation on the class path as dependency causes the transformation to be applied somehow.

**Comment by apryamostanov** [comment]
I would definitely recommend to avoid exporting this dependency in POM file, if this is possible/achievable.

**Comment by virtualdogbert** [comment]
A work around to this would be try apply the library directly to your project, and skipping the plugin:
`implementation 'com.virtualdogbert:enterprise-groovy:1.0.RC2'`

I'm going to add some documentation to this effect, the things you loose would be the groovy console, the ability to add a compilation script, and being able to run the setup. Although you could just add the plugin temporarily to get these features and then remove it. I'm thinking that the plugin might be good for adding to a project where the library might be better for adding to as library that gets reused.

**Comment by virtualdogbert** [comment]
Swapped compile with implementation, so it shouldn't become a transient dependency in other projects.

**Comment by apryamostanov** [comment]
Hi @virtualdogbert ,

Do I have to update the build.gradle on my side?

Without updating using RC3 it still has the dependency:
https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/PomView/oss-snapshot-local/io/infinite/supplies/1.0.1-SNAPSHOT/supplies-1.0.1-20190213.140427-34.pom

**Comment by virtualdogbert** [comment]
Ok I'll have to RTFM, I thought that, using implementation, made it not transient, but it looks like I may have to set a property for that.

**Comment by virtualdogbert** [comment]
This should be fixed in RC4 using compileOnly.
