### ISSUE TITLE
Removing JUnit 4.12 dependency

### ISSUE THREAD

**Issue by apryamostanov** [virtualdogbert/enterprise-groovy-plugin#9]
Hi @virtualdogbert !

If possible, would you be so kind to exclude JUnit 4.12 dependency in upcoming releases of Enterprise Groovy Plugin.

It is seems to cause the below issue using Grape:
```
@Grab('io.infinite:supplies:1.1.0')

String foobar(String foo) {
    String bar = "bar"
    String foobar = foo + bar
    return foobar
}

foobar("foo")
```
```
java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.junit.platform#junit-platform-engine;1.3.1!junit-platform-engine.jar]
```

PS: the workaround to avoid this error, in user build.gradle (where the Enterprise Groovy Plugin is applied):
```
configurations {
    providedRuntime
    compile.exclude(group: 'junit')
    compile.exclude(group: 'org.junit.platform')
}
```

**Comment by virtualdogbert** [comment]
Done wasn't using it any way in the project.
